alias ForgeNexus.Plugins
alias ForgeNexus.Plugins.Nodes.Registry
alias ForgeNexus.Repo
alias ForgeNexus.Accounts.User

IO.puts("=== Flow persistence test (create_flow_from_spec) ===\n")

# Find real node types to use
all = Registry.all_types() |> Enum.map(fn {type, _} -> type end)
trigger = Enum.find(all, &String.starts_with?(&1, "trigger/"))
logic = Enum.find(all, &String.starts_with?(&1, "logic/"))
action = Enum.find(all, fn t ->
  String.starts_with?(t, "notification/") or String.starts_with?(t, "action/")
end) || Enum.find(all, fn t -> not String.starts_with?(t, "trigger/") and not String.starts_with?(t, "logic/") end)

IO.puts("Trigger: #{trigger}")
IO.puts("Logic:   #{logic}")
IO.puts("Action:  #{action}")

[admin | _] = Repo.all(User) |> Enum.take(1)

spec = %{
  name: "Persistence Smoke Test",
  description: "Generated by test harness",
  trigger_type: trigger,
  trigger_config: %{},
  nodes: [
    %{client_id: "t1", type: trigger, label: "Start", config: %{}},
    %{client_id: "l1", type: logic, label: "Branch", config: %{}},
    %{client_id: "a1", type: action, label: "Do Thing", config: %{}}
  ],
  edges: [
    %{source: "t1", target: "l1", source_port: "output", target_port: "input"},
    %{source: "l1", target: "a1", source_port: "true", target_port: "input"}
  ]
}

case Plugins.create_flow_from_spec(spec, admin.id) do
  {:ok, flow} ->
    IO.puts("\n✓ flow inserted: #{flow.id}")
    IO.puts("  name: #{flow.name}")
    IO.puts("  slug: #{flow.slug}")
    IO.puts("  nodes: #{length(flow.nodes)}")
    IO.puts("  edges: #{length(flow.edges)}")

    unless length(flow.nodes) == 3 do
      IO.puts("✗ expected 3 nodes, got #{length(flow.nodes)}")
      System.halt(1)
    end

    unless length(flow.edges) == 2 do
      IO.puts("✗ expected 2 edges, got #{length(flow.edges)}")
      System.halt(1)
    end

    # Verify every edge's source/target is a real node id
    node_ids = MapSet.new(flow.nodes, & &1.id)

    Enum.each(flow.edges, fn edge ->
      unless MapSet.member?(node_ids, edge.source_node_id) do
        IO.puts("✗ edge source_node_id #{edge.source_node_id} not in nodes")
        System.halt(1)
      end

      unless MapSet.member?(node_ids, edge.target_node_id) do
        IO.puts("✗ edge target_node_id #{edge.target_node_id} not in nodes")
        System.halt(1)
      end
    end)

    IO.puts("✓ all edges reference real nodes")

    # Cleanup
    Plugins.delete_flow(flow.id)
    IO.puts("✓ cleaned up")

  {:error, reason} ->
    IO.puts("\n✗ create_flow_from_spec failed: #{inspect(reason)}")
    System.halt(1)
end

IO.puts("\n=== Flow persistence test passed ===")
