defmodule ForgeNexusWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :forge_nexus

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_forge_nexus_key",
    signing_salt: "IgO8HBN9",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", ForgeNexusWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :forge_nexus,
    gzip: not code_reloading?,
    only: ForgeNexusWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User-uploaded media. The release writes these to a CWD-relative path
  # ("priv/static/uploads") which docker-compose mounts as the `uploads`
  # named volume at `/app/priv/static/uploads`. Plug.Static above resolves
  # `:forge_nexus` to the release lib path (`/app/lib/forge_nexus-X/priv/static`),
  # so a separate static plug is needed to expose the volume publicly.
  plug Plug.Static,
    at: "/uploads",
    from: "/app/priv/static/uploads",
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :forge_nexus
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Sentry: capture context (request, user, etc.) for any error reports
  # downstream. PlugCapture is mounted INSIDE the router via use_error_handler,
  # but PlugContext attaches metadata to every request.
  plug Sentry.PlugContext

  # Max body size raised to 250 MB to accommodate voice recording uploads
  # (capped per-file by `voice_recording_max_size_mb`, default 200 MB).
  # Other endpoints should still be rate-limited at the reverse proxy layer.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 250_000_000,
    body_reader: {ForgeNexusWeb.Plugs.StripeRawBody, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ForgeNexusWeb.Plugs.Compress

  plug ForgeNexusWeb.Plugs.CORS
  plug ForgeNexusWeb.Plugs.CommunityResolver
  plug ForgeNexusWeb.Router
end
